spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: username
    password: password
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        connection:
          autocommit: true
        highlight_sql: true
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
    defer-datasource-initialization: true   #script run after hibernate init
  data:
    redis:
      host: 127.0.0.1   #${REDIS_URL}
      port: 6379
  sql:
    init:
      mode: always
      platform: h2

logging:
  level:
    org.hibernate.sql: info
    org.hibernate.type.descriptor.sql: trace

jwt:
  prefix: 'Bearer '
  secret-key: tj3io45htno453iht12312323123231121e12eeee3a1e1ee1e1e1e1e2eewe2ewnoi4253hntio2453ntio24ntio2ntionionion3io24ntoi32noti34noti
  access-token-validity-in-seconds: 150
  refresh-token-validity-in-seconds: 259200
  access-header: Authentication
  refresh-header: Refresh

cookie:
  limit-time: 259200
  accepted-url: '/api/auth/reissue'
  cookie-name: Refresh
  domain: localhost