spring:
  datasource:
    url: jdbc:mysql://${DATABASE_URL}:3306/lovlind?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
    password: ${DATABASE_PW}
    username: ${DATABASE_ID}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: 127.0.0.1   #${REDIS_URL}
      port: 6379
