spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lovlind?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
    password: wkaqh12Q!
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: 127.0.0.1   #${REDIS_URL}
      port: 6379
jwt:
  prefix: 'Bearer '
  secret-key: tj3io45htno453iht12312323123231121e12eeee3a1e1ee1e1e1e1e2eewe2ewnoi4253hntio2453ntio24ntio2ntionionion3io24ntoi32noti34noti
  access-token-validity-in-seconds: 150
  refresh-token-validity-in-seconds: 259200
  access-header: Authentication
  refresh-header: Refresh

cookie:
  limit-time: 259200
  accepted-url: '/api/auth/reissue'
  cookie-name: Refresh
  domain: localhost